version: '3.7'

services:
  mongodb:
    container_name: mongo_container
    image: mongo:5.0.8-focal
    environment:
      - MONGO_INITDB_DATABASE=nauticalDb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - nautical-network

  mongo-express:
    container_name: mongo_express_container
    image: mongo-express:0.54.0
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo_container
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://root:secret@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=express
    volumes:
      - ./data:/data/db
    ports:
      - "8081:8081"
    restart: always
    networks:
      - nautical-network

volumes:
  mongodb:
  mongo-express:

networks:
  nautical-network:
    name: nautical-network  